higan.components += wdc65816 spc700 arm7tdmi gsu hg51b upd96050

higan.objects += higan-sfc-interface higan-sfc-system higan-sfc-controller
higan.objects += higan-sfc-cartridge higan-sfc-memory
higan.objects += higan-sfc-cpu higan-sfc-smp higan-sfc-dsp higan-sfc-ppu
higan.objects += higan-sfc-coprocessor higan-sfc-expansion higan-sfc-slot

$(object.path)/higan-sfc-interface.o:   $(higan.path)/sfc/interface/interface.cpp
$(object.path)/higan-sfc-system.o:      $(higan.path)/sfc/system/system.cpp
$(object.path)/higan-sfc-controller.o:  $(higan.path)/sfc/controller/controller.cpp
$(object.path)/higan-sfc-cartridge.o:   $(higan.path)/sfc/cartridge/cartridge.cpp
$(object.path)/higan-sfc-memory.o:      $(higan.path)/sfc/memory/memory.cpp

$(object.path)/higan-sfc-cpu.o:         $(higan.path)/sfc/cpu/cpu.cpp
$(object.path)/higan-sfc-smp.o:         $(higan.path)/sfc/smp/smp.cpp
$(object.path)/higan-sfc-dsp.o:         $(higan.path)/sfc/dsp/dsp.cpp
$(object.path)/higan-sfc-ppu.o:         $(higan.path)/sfc/ppu/ppu.cpp

$(object.path)/higan-sfc-coprocessor.o: $(higan.path)/sfc/coprocessor/coprocessor.cpp
$(object.path)/higan-sfc-expansion.o:   $(higan.path)/sfc/expansion/expansion.cpp
$(object.path)/higan-sfc-slot.o:        $(higan.path)/sfc/slot/slot.cpp
