ares.components += z80 sn76489 ym2413

ares.objects += ares-ms-interface
ares.objects += ares-ms-cpu ares-ms-vdp ares-ms-psg ares-ms-opll
ares.objects += ares-ms-system ares-ms-cartridge
ares.objects += ares-ms-controller

$(object.path)/ares-ms-interface.o:  $(ares.path)/ms/interface/interface.cpp
$(object.path)/ares-ms-cpu.o:        $(ares.path)/ms/cpu/cpu.cpp
$(object.path)/ares-ms-vdp.o:        $(ares.path)/ms/vdp/vdp.cpp
$(object.path)/ares-ms-psg.o:        $(ares.path)/ms/psg/psg.cpp
$(object.path)/ares-ms-opll.o:       $(ares.path)/ms/opll/opll.cpp
$(object.path)/ares-ms-system.o:     $(ares.path)/ms/system/system.cpp
$(object.path)/ares-ms-cartridge.o:  $(ares.path)/ms/cartridge/cartridge.cpp
$(object.path)/ares-ms-controller.o: $(ares.path)/ms/controller/controller.cpp
