components += z80 sn76489 ym2413

objects += ms-interface
objects += ms-cpu ms-vdp ms-psg ms-opll
objects += ms-system ms-cartridge
objects += ms-controller

obj/ms-interface.o:  ms/interface/interface.cpp
obj/ms-cpu.o:        ms/cpu/cpu.cpp
obj/ms-vdp.o:        ms/vdp/vdp.cpp
obj/ms-psg.o:        ms/psg/psg.cpp
obj/ms-opll.o:       ms/opll/opll.cpp
obj/ms-system.o:     ms/system/system.cpp
obj/ms-cartridge.o:  ms/cartridge/cartridge.cpp
obj/ms-controller.o: ms/controller/controller.cpp
