higan.components += v30mz m93lcx6

higan.objects += higan-ws-interface higan-ws-system
higan.objects += higan-ws-memory higan-ws-eeprom higan-ws-cartridge
higan.objects += higan-ws-cpu higan-ws-ppu higan-ws-apu

$(object.path)/higan-ws-interface.o: $(higan.path)/ws/interface/interface.cpp
$(object.path)/higan-ws-system.o:    $(higan.path)/ws/system/system.cpp
$(object.path)/higan-ws-memory.o:    $(higan.path)/ws/memory/memory.cpp
$(object.path)/higan-ws-eeprom.o:    $(higan.path)/ws/eeprom/eeprom.cpp
$(object.path)/higan-ws-cartridge.o: $(higan.path)/ws/cartridge/cartridge.cpp
$(object.path)/higan-ws-cpu.o:       $(higan.path)/ws/cpu/cpu.cpp
$(object.path)/higan-ws-ppu.o:       $(higan.path)/ws/ppu/ppu.cpp
$(object.path)/higan-ws-apu.o:       $(higan.path)/ws/apu/apu.cpp
