higan.components += m68k z80 sn76489

higan.objects += higan-md-interface
higan.objects += higan-md-cpu higan-md-apu higan-md-vdp higan-md-psg higan-md-ym2612
higan.objects += higan-md-mcd
higan.objects += higan-md-system higan-md-cartridge higan-md-expansion
higan.objects += higan-md-controller

$(object.path)/higan-md-interface.o:  $(higan.path)/md/interface/interface.cpp
$(object.path)/higan-md-cpu.o:        $(higan.path)/md/cpu/cpu.cpp
$(object.path)/higan-md-apu.o:        $(higan.path)/md/apu/apu.cpp
$(object.path)/higan-md-vdp.o:        $(higan.path)/md/vdp/vdp.cpp
$(object.path)/higan-md-psg.o:        $(higan.path)/md/psg/psg.cpp
$(object.path)/higan-md-ym2612.o:     $(higan.path)/md/ym2612/ym2612.cpp
$(object.path)/higan-md-mcd.o:        $(higan.path)/md/mcd/mcd.cpp
$(object.path)/higan-md-system.o:     $(higan.path)/md/system/system.cpp
$(object.path)/higan-md-cartridge.o:  $(higan.path)/md/cartridge/cartridge.cpp
$(object.path)/higan-md-expansion.o:  $(higan.path)/md/expansion/expansion.cpp
$(object.path)/higan-md-controller.o: $(higan.path)/md/controller/controller.cpp
