components += m68k z80 sn76489

objects += md-interface
objects += md-cpu md-apu md-vdp md-psg md-ym2612
objects += md-mcd
objects += md-system md-cartridge md-expansion
objects += md-controller

obj/md-interface.o:  md/interface/interface.cpp
obj/md-cpu.o:        md/cpu/cpu.cpp
obj/md-apu.o:        md/apu/apu.cpp
obj/md-vdp.o:        md/vdp/vdp.cpp
obj/md-psg.o:        md/psg/psg.cpp
obj/md-ym2612.o:     md/ym2612/ym2612.cpp
obj/md-mcd.o:        md/mcd/mcd.cpp
obj/md-system.o:     md/system/system.cpp
obj/md-cartridge.o:  md/cartridge/cartridge.cpp
obj/md-expansion.o:  md/expansion/expansion.cpp
obj/md-controller.o: md/controller/controller.cpp
