higan.components += tlcs900h z80 t6w28

higan.objects += higan-ngp-interface higan-ngp-system higan-ngp-cartridge
higan.objects += higan-ngp-cpu higan-ngp-apu higan-ngp-vpu higan-ngp-psg

$(object.path)/higan-ngp-interface.o: $(higan.path)/ngp/interface/interface.cpp
$(object.path)/higan-ngp-system.o:    $(higan.path)/ngp/system/system.cpp
$(object.path)/higan-ngp-cartridge.o: $(higan.path)/ngp/cartridge/cartridge.cpp
$(object.path)/higan-ngp-cpu.o:       $(higan.path)/ngp/cpu/cpu.cpp
$(object.path)/higan-ngp-apu.o:       $(higan.path)/ngp/apu/apu.cpp
$(object.path)/higan-ngp-vpu.o:       $(higan.path)/ngp/vpu/vpu.cpp
$(object.path)/higan-ngp-psg.o:       $(higan.path)/ngp/psg/psg.cpp
