ares.components += huc6280 msm5205

ares.objects += ares-pce-interface
ares.objects += ares-pce-cpu ares-pce-vdp ares-pce-psg ares-pce-pcd
ares.objects += ares-pce-system ares-pce-cartridge
ares.objects += ares-pce-controller

$(object.path)/ares-pce-interface.o:  $(ares.path)/pce/interface/interface.cpp
$(object.path)/ares-pce-cpu.o:        $(ares.path)/pce/cpu/cpu.cpp
$(object.path)/ares-pce-vdp.o:        $(ares.path)/pce/vdp/vdp.cpp
$(object.path)/ares-pce-psg.o:        $(ares.path)/pce/psg/psg.cpp
$(object.path)/ares-pce-pcd.o:        $(ares.path)/pce/pcd/pcd.cpp
$(object.path)/ares-pce-system.o:     $(ares.path)/pce/system/system.cpp
$(object.path)/ares-pce-cartridge.o:  $(ares.path)/pce/cartridge/cartridge.cpp
$(object.path)/ares-pce-controller.o: $(ares.path)/pce/controller/controller.cpp
