higan.components += huc6280 msm5205

higan.objects += higan-pce-interface
higan.objects += higan-pce-cpu higan-pce-vdp higan-pce-psg higan-pce-pcd
higan.objects += higan-pce-system higan-pce-cartridge
higan.objects += higan-pce-controller

$(object.path)/higan-pce-interface.o:  $(higan.path)/pce/interface/interface.cpp
$(object.path)/higan-pce-cpu.o:        $(higan.path)/pce/cpu/cpu.cpp
$(object.path)/higan-pce-vdp.o:        $(higan.path)/pce/vdp/vdp.cpp
$(object.path)/higan-pce-psg.o:        $(higan.path)/pce/psg/psg.cpp
$(object.path)/higan-pce-pcd.o:        $(higan.path)/pce/pcd/pcd.cpp
$(object.path)/higan-pce-system.o:     $(higan.path)/pce/system/system.cpp
$(object.path)/higan-pce-cartridge.o:  $(higan.path)/pce/cartridge/cartridge.cpp
$(object.path)/higan-pce-controller.o: $(higan.path)/pce/controller/controller.cpp
