components += huc6280

objects += pce-interface
objects += pce-cpu pce-vdp pce-psg pce-pcd
objects += pce-system pce-cartridge
objects += pce-controller

obj/pce-interface.o:  pce/interface/interface.cpp
obj/pce-cpu.o:        pce/cpu/cpu.cpp
obj/pce-vdp.o:        pce/vdp/vdp.cpp
obj/pce-psg.o:        pce/psg/psg.cpp
obj/pce-pcd.o:        pce/pcd/pcd.cpp
obj/pce-system.o:     pce/system/system.cpp
obj/pce-cartridge.o:  pce/cartridge/cartridge.cpp
obj/pce-controller.o: pce/controller/controller.cpp
