struct AudioSettings : Panel {
  AudioSettings(View*);
  auto show() -> void override;
  auto hide() -> void override;

  Frame frame{this, Size{~0, ~0}};
  VerticalLayout layout{&frame};
  Label driverHeader{&layout, Size{~0, 0}};
  HorizontalLayout driverLayout{&layout, Size{~0, 0}};
    Label driverLabel{&driverLayout, Size{0, 0}};
    ComboButton driverOption{&driverLayout, Size{0, 0}};
  HorizontalLayout optionsLayout{&layout, Size{~0, 0}};
    Label deviceLabel{&optionsLayout, Size{0, 0}};
    ComboButton deviceOption{&optionsLayout, Size{0, 0}};
    Label frequencyLabel{&optionsLayout, Size{0, 0}};
    ComboButton frequencyOption{&optionsLayout, Size{0, 0}};
    Label latencyLabel{&optionsLayout, Size{0, 0}};
    ComboButton latencyOption{&optionsLayout, Size{0, 0}};
  HorizontalLayout togglesLayout{&layout, Size{~0, 0}};
    CheckLabel exclusiveOption{&togglesLayout, Size{0, 0}};
    CheckLabel synchronizeOption{&togglesLayout, Size{0, 0}};
    CheckLabel dynamicRateOption{&togglesLayout, Size{0, 0}};
  Label effectsHeader{&layout, Size{~0, 0}};
  TableLayout effectsLayout{&layout, Size{~0, 0}};
    Label skewLabel{&effectsLayout, Size{0, 0}};
    Label skewValue{&effectsLayout, Size{50_sx, 0}};
    HorizontalSlider skewSlider{&effectsLayout, Size{~0, 0}};
    Label volumeLabel{&effectsLayout, Size{0, 0}};
    Label volumeValue{&effectsLayout, Size{50_sx, 0}};
    HorizontalSlider volumeSlider{&effectsLayout, Size{~0, 0}};
    Label balanceLabel{&effectsLayout, Size{0, 0}};
    Label balanceValue{&effectsLayout, Size{50_sx, 0}};
    HorizontalSlider balanceSlider{&effectsLayout, Size{~0, 0}};
};
