components += z80 tms9918 sn76489

objects += sg-interface
objects += sg-cpu sg-vdp sg-psg
objects += sg-system sg-cartridge
objects += sg-controller

obj/sg-interface.o:  sg/interface/interface.cpp
obj/sg-cpu.o:        sg/cpu/cpu.cpp
obj/sg-vdp.o:        sg/vdp/vdp.cpp
obj/sg-psg.o:        sg/psg/psg.cpp
obj/sg-system.o:     sg/system/system.cpp
obj/sg-cartridge.o:  sg/cartridge/cartridge.cpp
obj/sg-controller.o: sg/controller/controller.cpp
