ares.components += mos6502 ym2149 ym2413 x24c01

ares.objects += ares-fc-interface ares-fc-system ares-fc-controller
ares.objects += ares-fc-cartridge ares-fc-cpu ares-fc-apu ares-fc-ppu
ares.objects += ares-fc-fds

$(object.path)/ares-fc-interface.o:  $(ares.path)/fc/interface/interface.cpp
$(object.path)/ares-fc-system.o:     $(ares.path)/fc/system/system.cpp
$(object.path)/ares-fc-controller.o: $(ares.path)/fc/controller/controller.cpp
$(object.path)/ares-fc-cartridge.o:  $(ares.path)/fc/cartridge/cartridge.cpp
$(object.path)/ares-fc-cpu.o:        $(ares.path)/fc/cpu/cpu.cpp
$(object.path)/ares-fc-apu.o:        $(ares.path)/fc/apu/apu.cpp
$(object.path)/ares-fc-ppu.o:        $(ares.path)/fc/ppu/ppu.cpp
$(object.path)/ares-fc-fds.o:        $(ares.path)/fc/fds/fds.cpp
