ares.components += wdc65816 spc700 arm7tdmi gsu hg51b upd96050

ares.objects += ares-sfc-interface ares-sfc-system ares-sfc-controller
ares.objects += ares-sfc-cartridge ares-sfc-memory
ares.objects += ares-sfc-cpu ares-sfc-smp ares-sfc-dsp ares-sfc-ppu
ares.objects += ares-sfc-coprocessor ares-sfc-expansion ares-sfc-slot

$(object.path)/ares-sfc-interface.o:   $(ares.path)/sfc/interface/interface.cpp
$(object.path)/ares-sfc-system.o:      $(ares.path)/sfc/system/system.cpp
$(object.path)/ares-sfc-controller.o:  $(ares.path)/sfc/controller/controller.cpp
$(object.path)/ares-sfc-cartridge.o:   $(ares.path)/sfc/cartridge/cartridge.cpp
$(object.path)/ares-sfc-memory.o:      $(ares.path)/sfc/memory/memory.cpp

$(object.path)/ares-sfc-cpu.o:         $(ares.path)/sfc/cpu/cpu.cpp
$(object.path)/ares-sfc-smp.o:         $(ares.path)/sfc/smp/smp.cpp
$(object.path)/ares-sfc-dsp.o:         $(ares.path)/sfc/dsp/dsp.cpp
$(object.path)/ares-sfc-ppu.o:         $(ares.path)/sfc/ppu/ppu.cpp

$(object.path)/ares-sfc-coprocessor.o: $(ares.path)/sfc/coprocessor/coprocessor.cpp
$(object.path)/ares-sfc-expansion.o:   $(ares.path)/sfc/expansion/expansion.cpp
$(object.path)/ares-sfc-slot.o:        $(ares.path)/sfc/slot/slot.cpp
