ares.components += arm7tdmi

ares.objects += ares-gba-memory ares-gba-interface ares-gba-system
ares.objects += ares-gba-cartridge ares-gba-player
ares.objects += ares-gba-cpu ares-gba-ppu ares-gba-apu

$(object.path)/ares-gba-memory.o:    $(ares.path)/gba/memory/memory.cpp
$(object.path)/ares-gba-interface.o: $(ares.path)/gba/interface/interface.cpp
$(object.path)/ares-gba-system.o:    $(ares.path)/gba/system/system.cpp
$(object.path)/ares-gba-cartridge.o: $(ares.path)/gba/cartridge/cartridge.cpp
$(object.path)/ares-gba-player.o:    $(ares.path)/gba/player/player.cpp
$(object.path)/ares-gba-cpu.o:       $(ares.path)/gba/cpu/cpu.cpp
$(object.path)/ares-gba-ppu.o:       $(ares.path)/gba/ppu/ppu.cpp
$(object.path)/ares-gba-apu.o:       $(ares.path)/gba/apu/apu.cpp
