higan.components += arm7tdmi

higan.objects += higan-gba-memory higan-gba-interface higan-gba-system
higan.objects += higan-gba-cartridge higan-gba-player
higan.objects += higan-gba-cpu higan-gba-ppu higan-gba-apu

$(object.path)/higan-gba-memory.o:    $(higan.path)/gba/memory/memory.cpp
$(object.path)/higan-gba-interface.o: $(higan.path)/gba/interface/interface.cpp
$(object.path)/higan-gba-system.o:    $(higan.path)/gba/system/system.cpp
$(object.path)/higan-gba-cartridge.o: $(higan.path)/gba/cartridge/cartridge.cpp
$(object.path)/higan-gba-player.o:    $(higan.path)/gba/player/player.cpp
$(object.path)/higan-gba-cpu.o:       $(higan.path)/gba/cpu/cpu.cpp
$(object.path)/higan-gba-ppu.o:       $(higan.path)/gba/ppu/ppu.cpp
$(object.path)/higan-gba-apu.o:       $(higan.path)/gba/apu/apu.cpp
