higan.components += mos6502 ym2149 ym2413 x24c01

higan.objects += higan-fc-interface higan-fc-system higan-fc-controller
higan.objects += higan-fc-cartridge higan-fc-cpu higan-fc-apu higan-fc-ppu
higan.objects += higan-fc-fds

$(object.path)/higan-fc-interface.o:  $(higan.path)/fc/interface/interface.cpp
$(object.path)/higan-fc-system.o:     $(higan.path)/fc/system/system.cpp
$(object.path)/higan-fc-controller.o: $(higan.path)/fc/controller/controller.cpp
$(object.path)/higan-fc-cartridge.o:  $(higan.path)/fc/cartridge/cartridge.cpp
$(object.path)/higan-fc-cpu.o:        $(higan.path)/fc/cpu/cpu.cpp
$(object.path)/higan-fc-apu.o:        $(higan.path)/fc/apu/apu.cpp
$(object.path)/higan-fc-ppu.o:        $(higan.path)/fc/ppu/ppu.cpp
$(object.path)/higan-fc-fds.o:        $(higan.path)/fc/fds/fds.cpp
