ares.components += z80 tms9918 v9938 ay38910 ym2413

ares.objects += ares-msx-interface ares-msx-system ares-msx-keyboard
ares.objects += ares-msx-cartridge ares-msx-controller
ares.objects += ares-msx-cpu ares-msx-vdp ares-msx-psg

$(object.path)/ares-msx-interface.o:  $(ares.path)/msx/interface/interface.cpp
$(object.path)/ares-msx-system.o:     $(ares.path)/msx/system/system.cpp
$(object.path)/ares-msx-keyboard.o:   $(ares.path)/msx/keyboard/keyboard.cpp
$(object.path)/ares-msx-cartridge.o:  $(ares.path)/msx/cartridge/cartridge.cpp
$(object.path)/ares-msx-controller.o: $(ares.path)/msx/controller/controller.cpp
$(object.path)/ares-msx-cpu.o:        $(ares.path)/msx/cpu/cpu.cpp
$(object.path)/ares-msx-vdp.o:        $(ares.path)/msx/vdp/vdp.cpp
$(object.path)/ares-msx-psg.o:        $(ares.path)/msx/psg/psg.cpp
