higan.objects += higan-ps1-interface
higan.objects += higan-ps1-memory
higan.objects += higan-ps1-system
higan.objects += higan-ps1-disc
higan.objects += higan-ps1-controller
higan.objects += higan-ps1-cpu
higan.objects += higan-ps1-gpu
higan.objects += higan-ps1-spu
higan.objects += higan-ps1-mdec
higan.objects += higan-ps1-interrupt
higan.objects += higan-ps1-peripheral
higan.objects += higan-ps1-dma
higan.objects += higan-ps1-timer

$(object.path)/higan-ps1-interface.o:  $(higan.path)/ps1/interface/interface.cpp
$(object.path)/higan-ps1-memory.o:     $(higan.path)/ps1/memory/memory.cpp
$(object.path)/higan-ps1-system.o:     $(higan.path)/ps1/system/system.cpp
$(object.path)/higan-ps1-controller.o: $(higan.path)/ps1/controller/controller.cpp
$(object.path)/higan-ps1-disc.o:       $(higan.path)/ps1/disc/disc.cpp
$(object.path)/higan-ps1-cpu.o:        $(higan.path)/ps1/cpu/cpu.cpp
$(object.path)/higan-ps1-gpu.o:        $(higan.path)/ps1/gpu/gpu.cpp
$(object.path)/higan-ps1-spu.o:        $(higan.path)/ps1/spu/spu.cpp
$(object.path)/higan-ps1-mdec.o:       $(higan.path)/ps1/mdec/mdec.cpp
$(object.path)/higan-ps1-interrupt.o:  $(higan.path)/ps1/interrupt/interrupt.cpp
$(object.path)/higan-ps1-peripheral.o: $(higan.path)/ps1/peripheral/peripheral.cpp
$(object.path)/higan-ps1-dma.o:        $(higan.path)/ps1/dma/dma.cpp
$(object.path)/higan-ps1-timer.o:      $(higan.path)/ps1/timer/timer.cpp
