higan.objects += higan-n64-interface higan-n64-memory higan-n64-system
higan.objects += higan-n64-cartridge higan-n64-controller higan-n64-dd
higan.objects += higan-n64-mi higan-n64-vi higan-n64-ai
higan.objects += higan-n64-pi higan-n64-ri higan-n64-si
higan.objects += higan-n64-rdram higan-n64-cpu higan-n64-rdp higan-n64-rsp

$(object.path)/higan-n64-interface.o:  $(higan.path)/n64/interface/interface.cpp
$(object.path)/higan-n64-memory.o:     $(higan.path)/n64/memory/memory.cpp
$(object.path)/higan-n64-system.o:     $(higan.path)/n64/system/system.cpp
$(object.path)/higan-n64-cartridge.o:  $(higan.path)/n64/cartridge/cartridge.cpp
$(object.path)/higan-n64-controller.o: $(higan.path)/n64/controller/controller.cpp
$(object.path)/higan-n64-dd.o:         $(higan.path)/n64/dd/dd.cpp
$(object.path)/higan-n64-sp.o:         $(higan.path)/n64/sp/sp.cpp
$(object.path)/higan-n64-dp.o:         $(higan.path)/n64/dp/dp.cpp
$(object.path)/higan-n64-mi.o:         $(higan.path)/n64/mi/mi.cpp
$(object.path)/higan-n64-vi.o:         $(higan.path)/n64/vi/vi.cpp
$(object.path)/higan-n64-ai.o:         $(higan.path)/n64/ai/ai.cpp
$(object.path)/higan-n64-pi.o:         $(higan.path)/n64/pi/pi.cpp
$(object.path)/higan-n64-ri.o:         $(higan.path)/n64/ri/ri.cpp
$(object.path)/higan-n64-si.o:         $(higan.path)/n64/si/si.cpp
$(object.path)/higan-n64-rdram.o:      $(higan.path)/n64/rdram/rdram.cpp
$(object.path)/higan-n64-cpu.o:        $(higan.path)/n64/cpu/cpu.cpp
$(object.path)/higan-n64-rdp.o:        $(higan.path)/n64/rdp/rdp.cpp
$(object.path)/higan-n64-rsp.o:        $(higan.path)/n64/rsp/rsp.cpp

flags += -msse4.2
options += -msse4.2
