ares.components += v30mz m93lcx6

ares.objects += ares-ws-interface ares-ws-system
ares.objects += ares-ws-memory ares-ws-eeprom ares-ws-cartridge
ares.objects += ares-ws-cpu ares-ws-ppu ares-ws-apu

$(object.path)/ares-ws-interface.o: $(ares.path)/ws/interface/interface.cpp
$(object.path)/ares-ws-system.o:    $(ares.path)/ws/system/system.cpp
$(object.path)/ares-ws-memory.o:    $(ares.path)/ws/memory/memory.cpp
$(object.path)/ares-ws-eeprom.o:    $(ares.path)/ws/eeprom/eeprom.cpp
$(object.path)/ares-ws-cartridge.o: $(ares.path)/ws/cartridge/cartridge.cpp
$(object.path)/ares-ws-cpu.o:       $(ares.path)/ws/cpu/cpu.cpp
$(object.path)/ares-ws-ppu.o:       $(ares.path)/ws/ppu/ppu.cpp
$(object.path)/ares-ws-apu.o:       $(ares.path)/ws/apu/apu.cpp
