ares.components += vr4300

ares.objects += ares-n64-interface ares-n64-system
ares.objects += ares-n64-cartridge ares-n64-controller
ares.objects += ares-n64-cpu ares-n64-rdp ares-n64-rsp

$(object.path)/ares-n64-interface.o:  $(ares.path)/n64/interface/interface.cpp
$(object.path)/ares-n64-system.o:     $(ares.path)/n64/system/system.cpp
$(object.path)/ares-n64-cartridge.o:  $(ares.path)/n64/cartridge/cartridge.cpp
$(object.path)/ares-n64-controller.o: $(ares.path)/n64/controller/controller.cpp
$(object.path)/ares-n64-cpu.o:        $(ares.path)/n64/cpu/cpu.cpp
$(object.path)/ares-n64-rdp.o:        $(ares.path)/n64/rdp/rdp.cpp
$(object.path)/ares-n64-rsp.o:        $(ares.path)/n64/rsp/rsp.cpp
