components += sm83 m93lcx6

objects += gb-interface gb-system
objects += gb-bus gb-cartridge
objects += gb-cpu gb-ppu gb-apu

obj/gb-interface.o: gb/interface/interface.cpp
obj/gb-system.o:    gb/system/system.cpp
obj/gb-cartridge.o: gb/cartridge/cartridge.cpp
obj/gb-bus.o:       gb/bus/bus.cpp
obj/gb-cpu.o:       gb/cpu/cpu.cpp
obj/gb-ppu.o:       gb/ppu/ppu.cpp
obj/gb-apu.o:       gb/apu/apu.cpp
