higan.components += sm83 m93lcx6

higan.objects += higan-gb-interface higan-gb-system
higan.objects += higan-gb-bus higan-gb-cartridge
higan.objects += higan-gb-cpu higan-gb-ppu higan-gb-apu

$(object.path)/higan-gb-interface.o: $(higan.path)/gb/interface/interface.cpp
$(object.path)/higan-gb-system.o:    $(higan.path)/gb/system/system.cpp
$(object.path)/higan-gb-cartridge.o: $(higan.path)/gb/cartridge/cartridge.cpp
$(object.path)/higan-gb-bus.o:       $(higan.path)/gb/bus/bus.cpp
$(object.path)/higan-gb-cpu.o:       $(higan.path)/gb/cpu/cpu.cpp
$(object.path)/higan-gb-ppu.o:       $(higan.path)/gb/ppu/ppu.cpp
$(object.path)/higan-gb-apu.o:       $(higan.path)/gb/apu/apu.cpp
