higan.components += z80 tms9918 v9938 ay38910 ym2413

higan.objects += higan-msx-interface higan-msx-system higan-msx-keyboard
higan.objects += higan-msx-cartridge higan-msx-controller
higan.objects += higan-msx-cpu higan-msx-vdp higan-msx-psg

$(object.path)/higan-msx-interface.o:  $(higan.path)/msx/interface/interface.cpp
$(object.path)/higan-msx-system.o:     $(higan.path)/msx/system/system.cpp
$(object.path)/higan-msx-keyboard.o:   $(higan.path)/msx/keyboard/keyboard.cpp
$(object.path)/higan-msx-cartridge.o:  $(higan.path)/msx/cartridge/cartridge.cpp
$(object.path)/higan-msx-controller.o: $(higan.path)/msx/controller/controller.cpp
$(object.path)/higan-msx-cpu.o:        $(higan.path)/msx/cpu/cpu.cpp
$(object.path)/higan-msx-vdp.o:        $(higan.path)/msx/vdp/vdp.cpp
$(object.path)/higan-msx-psg.o:        $(higan.path)/msx/psg/psg.cpp
