components += z80 tms9918 v9938 ay38910 ym2413

objects += msx-interface msx-system msx-keyboard
objects += msx-cartridge msx-controller
objects += msx-cpu msx-vdp msx-psg

obj/msx-interface.o:  msx/interface/interface.cpp
obj/msx-system.o:     msx/system/system.cpp
obj/msx-keyboard.o:   msx/keyboard/keyboard.cpp
obj/msx-cartridge.o:  msx/cartridge/cartridge.cpp
obj/msx-controller.o: msx/controller/controller.cpp
obj/msx-cpu.o:        msx/cpu/cpu.cpp
obj/msx-vdp.o:        msx/vdp/vdp.cpp
obj/msx-psg.o:        msx/psg/psg.cpp
