higan.components += z80 sn76489 ym2413

higan.objects += higan-ms-interface
higan.objects += higan-ms-cpu higan-ms-vdp higan-ms-psg higan-ms-opll
higan.objects += higan-ms-system higan-ms-cartridge
higan.objects += higan-ms-controller

$(object.path)/higan-ms-interface.o:  $(higan.path)/ms/interface/interface.cpp
$(object.path)/higan-ms-cpu.o:        $(higan.path)/ms/cpu/cpu.cpp
$(object.path)/higan-ms-vdp.o:        $(higan.path)/ms/vdp/vdp.cpp
$(object.path)/higan-ms-psg.o:        $(higan.path)/ms/psg/psg.cpp
$(object.path)/higan-ms-opll.o:       $(higan.path)/ms/opll/opll.cpp
$(object.path)/higan-ms-system.o:     $(higan.path)/ms/system/system.cpp
$(object.path)/higan-ms-cartridge.o:  $(higan.path)/ms/cartridge/cartridge.cpp
$(object.path)/higan-ms-controller.o: $(higan.path)/ms/controller/controller.cpp
