ares.objects += ares-ps1-interface ares-ps1-system

$(object.path)/ares-ps1-interface.o: $(ares.path)/ps1/interface/interface.cpp
$(object.path)/ares-ps1-system.o:    $(ares.path)/ps1/system/system.cpp
