ares.objects += ares-ps1-interface ares-ps1-memory ares-ps1-system
ares.objects += ares-ps1-cpu ares-ps1-gpu ares-ps1-spu

$(object.path)/ares-ps1-interface.o: $(ares.path)/ps1/interface/interface.cpp
$(object.path)/ares-ps1-memory.o:    $(ares.path)/ps1/memory/memory.cpp
$(object.path)/ares-ps1-system.o:    $(ares.path)/ps1/system/system.cpp
$(object.path)/ares-ps1-cpu.o:       $(ares.path)/ps1/cpu/cpu.cpp
$(object.path)/ares-ps1-gpu.o:       $(ares.path)/ps1/gpu/gpu.cpp
$(object.path)/ares-ps1-spu.o:       $(ares.path)/ps1/spu/spu.cpp
