ares.components += tlcs900h z80 t6w28

ares.objects += ares-ngp-interface ares-ngp-system ares-ngp-cartridge
ares.objects += ares-ngp-cpu ares-ngp-apu ares-ngp-vpu ares-ngp-psg

$(object.path)/ares-ngp-interface.o: $(ares.path)/ngp/interface/interface.cpp
$(object.path)/ares-ngp-system.o:    $(ares.path)/ngp/system/system.cpp
$(object.path)/ares-ngp-cartridge.o: $(ares.path)/ngp/cartridge/cartridge.cpp
$(object.path)/ares-ngp-cpu.o:       $(ares.path)/ngp/cpu/cpu.cpp
$(object.path)/ares-ngp-apu.o:       $(ares.path)/ngp/apu/apu.cpp
$(object.path)/ares-ngp-vpu.o:       $(ares.path)/ngp/vpu/vpu.cpp
$(object.path)/ares-ngp-psg.o:       $(ares.path)/ngp/psg/psg.cpp
