ares.components += m68k z80 sn76489

ares.objects += ares-md-interface
ares.objects += ares-md-cpu ares-md-apu ares-md-vdp ares-md-psg ares-md-ym2612
ares.objects += ares-md-mcd
ares.objects += ares-md-system ares-md-cartridge ares-md-expansion
ares.objects += ares-md-controller

$(object.path)/ares-md-interface.o:  $(ares.path)/md/interface/interface.cpp
$(object.path)/ares-md-cpu.o:        $(ares.path)/md/cpu/cpu.cpp
$(object.path)/ares-md-apu.o:        $(ares.path)/md/apu/apu.cpp
$(object.path)/ares-md-vdp.o:        $(ares.path)/md/vdp/vdp.cpp
$(object.path)/ares-md-psg.o:        $(ares.path)/md/psg/psg.cpp
$(object.path)/ares-md-ym2612.o:     $(ares.path)/md/ym2612/ym2612.cpp
$(object.path)/ares-md-mcd.o:        $(ares.path)/md/mcd/mcd.cpp
$(object.path)/ares-md-system.o:     $(ares.path)/md/system/system.cpp
$(object.path)/ares-md-cartridge.o:  $(ares.path)/md/cartridge/cartridge.cpp
$(object.path)/ares-md-expansion.o:  $(ares.path)/md/expansion/expansion.cpp
$(object.path)/ares-md-controller.o: $(ares.path)/md/controller/controller.cpp
