components += z80 tms9918 sn76489

objects += cv-interface
objects += cv-cpu cv-vdp cv-psg
objects += cv-system cv-cartridge
objects += cv-controller

obj/cv-interface.o:  cv/interface/interface.cpp
obj/cv-cpu.o:        cv/cpu/cpu.cpp
obj/cv-vdp.o:        cv/vdp/vdp.cpp
obj/cv-psg.o:        cv/psg/psg.cpp
obj/cv-system.o:     cv/system/system.cpp
obj/cv-cartridge.o:  cv/cartridge/cartridge.cpp
obj/cv-controller.o: cv/controller/controller.cpp
