name: Build
on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        program:
        - higan-ui
        - icarus
        os:
        - name: ubuntu
          version: latest
        - name: windows
          version: latest
        - name: macos
          version: latest
    runs-on: ${{ matrix.os.name }}-${{ matrix.os.version }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      if: matrix.os.name == 'ubuntu'
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev libgtk-3-dev gtksourceview-3.0 libao-dev libopenal-dev
    - name: Make
      run: make -j4 -C ${{ matrix.program }} build=performance local=false
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.program }}-${{ matrix.os.name }}
        path: ${{ matrix.program }}/out/*

  release:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
    - uses: actions/checkout@v4
      with:
        path: 'src'
    - name: Download Artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        path: 'bin'
    - name: Package Artifacts
      run: |
        set -eu
        case ${GITHUB_REF} in
          refs/tags/*) suffix="-${GITHUB_REF#refs/tags/}" ;;
          refs/heads/master) suffix="-nightly" ;;
          *) suffix="" ;;
        esac

        srcdir="${GITHUB_WORKSPACE}/src"
        bindir="${GITHUB_WORKSPACE}/bin"

        # Hack: Workaround for GitHub artifacts losing attributes.
        for program in higan-ui icarus
        do
          chmod +x ${bindir}/${program}-ubuntu/*
          chmod +x ${bindir}/${program}-macos/*/Contents/MacOS/*
        done

        for os in ubuntu windows macos
        do
          mkdir "${os}"
          cd "${os}"

          # Package higan.
          outdir=higan${suffix}
          mkdir ${outdir}
          mkdir ${outdir}/Systems
          cp -ar ${bindir}/higan-ui-${os}/* ${outdir}
          cp -ar ${bindir}/icarus-${os}/* ${outdir}
          cp -a ${srcdir}/higan/System ${outdir}/Templates
          cp -a ${srcdir}/icarus/Database ${outdir}
          cp -a ${srcdir}/icarus/Firmware ${outdir}
          cp -a ${srcdir}/GPLv3.txt ${outdir}
          cp -a ${srcdir}/extras/* ${outdir}
          zip -r ../higan-${os}.zip ${outdir}

          cd -
        done

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          higan-ubuntu.zip
          higan-windows.zip
          higan-macos.zip
        name: ${{ startsWith(github.ref, 'refs/tags/') && format('higan {0}', github.ref_name) || format('higan nightly {0}', github.event.repository.updated_at) }}
        tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'nightly' }}
        prerelease: ${{ github.ref == 'refs/heads/master' }}
        body: ${{ startsWith(github.ref, 'refs/tags/') && format('This is higan {0}, released on {1}', github.ref_name, github.event.repository.updated_at) || format('Auto-generated nightly release on {0}', github.event.repository.updated_at) }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
